name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24.x

    - name: Install rebar3
      run: |
        wget https://s3.amazonaws.com/rebar3/rebar3
        chmod +x rebar3
        sudo mv rebar3 /usr/local/bin/

    - name: Install dependencies
      run: rebar3 get-deps

    - name: Run tests
      run: rebar3 eunit
