name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: 24.x

    - name: Install dependencies
      run: rebar3 get-deps

    - name: Run tests
      run: rebar3 eunit
