name: Test and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.x
          rebar3-version: 3.16.1

      - name: Install dependencies
        run: rebar3 get-deps

      - name: Run unit tests
        run: rebar3 eunit --verbose

      - name: Run integration tests
        run: rebar3 ct --verbose
